class Profession:
    def __init__(self, code, name_m, name_f, icon_str, description, perspective_prompt):
        self.code = code
        self.name_m = name_m
        self.name_f = name_f
        self.icon_str = icon_str
        self.description = description
        self.perspective_prompt = perspective_prompt

    def get_title(self, gender="m"):
        if gender == "f":
            return self.name_f
        elif gender == "both":
            return f"{self.name_m} / {self.name_f}"
        return self.name_m

ALL_PROFESSIONS = [
   # Finanzen, Banking, Börse & Versicherung
    Profession("BANKER", "Bankier / Bankkaufmann", "Bankier / Bankkauffrau", "🏦", 
               "Kreditwesen, Liquidität & Kapitalanlage",
               "Bewertet Risiken, Kreditwürdigkeiten, Zinsentwicklungen und Kapitalflüsse."),
    Profession("VOLKSWIRT", "Volkswirt / Ökonom", "Volkswirtin / Ökonomin", "📈", 
               "Makroökonomie, Marktmechanismen & Konjunktur",
               "Analysiert volkswirtschaftliche Zusammenhänge, Inflation, Geldpolitik und Marktstrukturen."),
    Profession("FINANZWIRT", "Finanzwirt / Steuerprüfer", "Finanzwirtin / Steuerprüferin", "📊", 
               "Steuerrecht, Abgabenordnung & Fiskalpolitik",
               "Prüft Bilanzen, Steuererklärungen, rechtliche Rahmenbedingungen und fiskalische Compliance."),
    Profession("BOERSENMAKLER", "Börsenmakler / Händler", "Börsenmaklerin / Händlerin", "📉", 
               "Wertpapierhandel, Marktvolatilität & Spekulation",
               "Bewertet Aktienkurse, Marktpsychologie, Orderbücher und Handelsrisiken."),
    Profession("VERSICHERUNGSKAUFMANN", "Versicherungsfachmann / Aktuar", "Versicherungsfachfrau / Aktuarin", "🛡️", 
               "Risikobewertung, Schadensfall & Police",
               "Kalkuliert Schadensrisiken, Deckungssummen, Rückstellungen und Versicherungspolicen."), # Theater, Film, Medien & Fotografie
    Profession("REGISSEUR", "Regisseur", "Regisseurin", "🎬", 
               "Mise en Scène, Inszenierung & Handlungsführung",
               "Bewertet das Geschehen nach dramatischer Führung, Raumaufteilung, Führung der Protagonisten und visueller Wirkung."),
    Profession("SCHAUSPIELER", "Schauspieler", "Schauspielerin", "🎭", 
               "Mimik, Rollen-Empathie, Habitus & Gestik",
               "Liest Texte und Situationen durch die Motivation der Charaktere, Maskeraden, Verstellung und Körpersprache."),
    Profession("DRAMATURG", "Dramaturg", "Dramaturgin", "📜", 
               "Subtext-Analyse, Spannungsbogen & Textkritik",
               "Zerlegt die Struktur nach dramatischen Bögen, inneren Widersprüchen, Subtexten und narrativer Kohärenz."),
    Profession("PHOTOGRAPH", "Fotograf / Photograph", "Fotografin / Photographin", "📷", 
               "Lichtbrechung, Belichtung & Optische Dokumentation",
               "Analysiert Perspektiven, Schärfentiefe, Bildkomposition, Lichtschatten und den eingefrorenen Augenblick."),
    Profession("JOURNALIST", "Journalist", "Journalistin", "📰", 
               "Recherche, Quellenprüfung & Faktencheck",
               "Prüft Aussagen auf Wahrheitsgehalt, Informationsquellen, Veröffentlichungsinteresse und journalistische Sorgfalt."),

    # Sakral, Hermetik, Ritus & Dichtung
    Profession("PAPST", "Papst / Pontifex", "Päpstin / Pontifex", "🇻🇦", 
               "Dogmatik, Kanonisches Recht & Vatikans-Archiv",
               "Analysiert Dokumente unter dem Aspekt sakraler Legitimität, kanonischem Recht und dogmatischer Reinheit."),
    Profession("PRIESTER", "Priester", "Priesterin", "✝️", 
               "Liturgie, Seelsorge, Sakramente & Exegese",
               "Bewertet Texte nach geistlicher Führung, seelsorgerischer Tragweite, Glaubenslehre und liturgischem Ritus."),
    Profession("MAGIER", "Magier / Alchemist", "Magierin / Alchemistin", "🔮", 
               "Opus Magnum, Spagyrik & Hermetik",
               "Sucht nach Hermetik, verborgenen Symbolen, astrologischen Korrespondenzen und Wandlungsprozessen."),
    Profession("SCHAMANE", "Schamane", "Schamanin", "🌀", 
               "Geomantie, Ahnen-Schau & Ley-Linien",
               "Liest die feinstofflichen Energien des Geländes, Ahnenverbindungen und sakral-topographische Muster."),
    Profession("DICHTER", "Dichterfürst", "Dichterfürstin", "🪶", 
               "Mythos, Logos-Verdichtung & Manifeste",
               "Konzentriert sich auf Rhythmus, Metaphorik, rhetorische Durchschlagskraft und Mythenbildung."),

    # Bestattung, Sepulkralkultur & Sargbau
    Profession("BESTATTER", "Bestatter", "Bestatterin", "⚰️", 
               "Thanatopraxie, Aufbahrung & Sepulkralkultur",
               "Analysiert Riten des Übergangs, Konservierung, Beisetzungsformen und historische Sepulkralkultur."),
    Profession("SARGBAUER", "Sargbauer", "Sargbauerin", "🪵", 
               "Sepulkral-Tischlerei, Zinkeinlagen & Holzversiegelung",
               "Prüft Holzbeständigkeit, Dichtigkeit, Zinkblech-Auskleidungen und Passgenauigkeit für die ewige Ruhe."),

    # Souveränität, Staat & Handel
    Profession("MONARCH", "Monarch", "Monarchin", "👑", 
               "Legitimität, Kabinettsordnungen & Dynastie",
               "Betrachtet den Text durch die Linse staatlicher Souveränität, Erbfolge und dynastischer Interessen."),
    Profession("JURIST", "Jurist", "Juristin", "⚖️", 
               "Vertragsrecht, Eigentumstitel & Legalität",
               "Examiniert Formfehler, Klauseln, Haftungsfragen und die unumstößliche Rechtsgültigkeit."),
    Profession("POLITIKER", "Politiker", "Politikerin", "🏛️", 
               "Geopolitik, Polis-Analyse & Machtbilanz",
               "Bewertet Bündnisoptionen, öffentliche Wirkung, strategische Interessen und Machtdynamiken."),
    Profession("KAUFMANN", "Kaufmann", "Kauffrau", "🪙", 
               "Handel, Kontor, Logistik & Wechselbriefe",
               "Berechnet Handelsspannen, Währungsstabilität, Transportrisiken und kaufmännische Bilanzen."),
    Profession("PINKERTON", "Geheimdienstler", "Geheimdienstlerin", "🕵️", 
               "Arcana Imperii, Personendossiers & Netze",
               "Filtert nach versteckten Hinweisen, Netzwerken, Doppelidentitäten und Spionage-Momenten."),
    Profession("SOLDAT", "Soldat", "Soldatin", "⚔️", 
               "Taktik, Geländebeurteilung & Strategie",
               "Bewertet Geländevorteile, logistische Schwachstellen, Verteidigungsfähigkeiten und Taktik."),

    # Druck, Typografie, Grafik & Medien
    Profession("DRUCKER", "Drucker", "Druckerin", "🖨️", 
               "Druckgrafik, Pigmentauftrag & Gutenberg-Kunst",
               "Prüft Papierqualität, Druckerschwärze, Satzspiegel, Plattenabnutzung und Druckauflagen."),
    Profession("SCHRIFTSETZER", "Schriftsetzer", "Schriftsetzerin", "🔤", 
               "Bleisatz, Gutenberg-Taxonomie & Setzkasten",
               "Achtet auf Typografie, Spationierung, Ligaturen, Zeilenabstand und korrekten Bleisatz."),
    Profession("GRAFIKER", "Grafiker / Visualist", "Grafikerin / Visualistin", "🎨", 
               "Visuelle Semiotik, Symbolik & Layout",
               "Analysiert Komposition, Farbharmonie, Bildrhetorik, Heraldik und grafische Symbolsprache."),

    # Architektur, Bau & Holzverarbeitung
    Profession("ARCHITEKT", "Architekt", "Architektin", "📐", 
               "Entwurfslehre, Proportionalität & Raumgeometrie",
               "Beurteilt Entwurfsästhetik, Raumkonzepte, Fassadengliederung und funktionale Gebäudeplanung."),
    Profession("LANDSCHAFTSARCHITEKT", "Landschaftsarchitekt", "Landschaftsarchitektin", "🌳", 
               "Freiraumplanung, Landschaftsökologie & Grünanlagen",
               "Analysiert Geländestrukturen, Bepflanzungskonzepte, Freiraumästhetik und ökologische Gestaltung."),
    Profession("ZIMMERMANN", "Zimmermann", "Zimmerin", "🪓", 
               "Fachwerkbau, Dachstuhl-Statik & Abbundkunst",
               "Examiniert Holzkonstruktionen, Zinkennägel, Dachstühle, Holzverbindungen und Lasteinwirkung."),
    Profession("BAUMEISTER", "Baumeister", "Baumeisterin", "🏗️", 
               "Statik, Sakralgeometrie & Archivbau",
               "Prüft die Architektur, Proportionalität, Tragwerk und sakralgeometrische Fundamente."),
    Profession("INGENIEUR", "Ingenieur", "Ingenieurin", "⚙️", 
               "Thermodynamik, Anorganik & Mechanik",
               "Untersucht Materialeigenschaften, technische Machbarkeit, Antriebe und Effizienz."),
    Profession("BOOTSBAUER", "Bootsbauer", "Bootsbauerin", "🛶", 
               "Schiffbau, Spantenkonstruktion & Hydrodynamik",
               "Examiniert Holzbiegung, Dichtigkeit, Tragfähigkeit von Schiffsrümpfen und maritime Tauglichkeit."),
    Profession("SCHMIED", "Schmied", "Schmiedin", "🔨", 
               "Metallverarbeitung, Feuerführung & Gefügekunde",
               "Beurteilt Legierungen, Härtegrade, Schmiedefeuer-Techniken und werkstoffkundliche Belastung."),
    Profession("GOLDSCHMIED", "Goldschmied", "Goldschmiedin", "💎", 
               "Edelmetallverarbeitung, Karat & Ziseleurkunst",
               "Prüft Reinheitsgrade von Edelmetallen, Fassungen, Stempelungen und feine Juwelierkunst."),
    Profession("KAPITAEN", "Schiffskapitän", "Schiffskapitänin", "⚓", 
               "Nautik, Ozeanische Logistik & Navigation",
               "Liest Winde, Strömungen, maritime Handelswege und nautische Herausforderungen."),

    # Instrumentenbau & Musik
    Profession("GEIGENBAUER", "Geigenbauer / Luthier", "Geigenbauerin / Luthier", "🎻", 
               "Resonanzholz, Lackzusammensetzung & Wölbung",
               "Untersucht Fichten- und Ahornhölzer, Klangholzlacke, Wölbungen und akustische Eigenresonanz."),
    Profession("GITARRENBAUER", "Gitarrenbauer", "Gitarrenbauerin", "🎸", 
               "Zargenbiegung, Mensur & Beplankung",
               "Analysiert Mensurlängen, Halsneigung, Brückenkonstruktion und Beplankung von Klangkörpern."),
    Profession("INSTRUMENTENBAUER", "Instrumentenbauer (Blech/Holz)", "Instrumentenbauerin (Blech/Holz)", "🎺", 
               "Messingverarbeitung, Intonation & Mensurierung",
               "Beurteilt Metalllegierungen, Wandstärken, Ventilmashinerie und akustische Schwingungsverläufe."),
    Profession("MUSIKER", "Klang-Hermetiker", "Klang-Hermetikerin", "🎼", 
               "Harmonik, Frequenz-Resonanz & Rhythmus",
               "Liest die Schwingungen, intervalischen Entsprechungen und akustischen Resonanzräume."),

    # Handwerk, Textil, Ton & Glas
    Profession("SCHNEIDER", "Schneider", "Schneiderin", "✂️", 
               "Textilhandwerk, Gewandung & Maßarbeit",
               "Achtet auf Stoffqualitäten, Webmuster, Verstecke im Saum und ständische Kleidungscodes."),
    Profession("SCHUSTER", "Schuster / Schuhmacher", "Schusterin / Schuhmacherin", "👞", 
               "Lederverarbeitung, Leisten & Passform",
               "Analysiert Abnutzungsmuster, Ledergerbung, Hohlräume in Absätzen und Fußspuren."),
    Profession("TOEPFER", "Töpfer", "Töpferin", "🏺", 
               "Keramik, Brennofen & Tonverarbeitung",
               "Liest Tonmineralien, Glasurtechniken, Brenntemperaturen und Gefäßarchäologie."),
    Profession("GLASER", "Glaser", "Glaserin", "🪟", 
               "Glaskunst, Schmelztechnik & Fenstersatz",
               "Beurteilt Lichtbrechung, Quarzzusammensetzung, Bleiverglasung und Glasreinheit."),
    Profession("SCHREINER", "Schreiner / Tischler", "Schreinerin / Tischlerin", "🪵", 
               "Holzbearbeitung, Verzinkung & Möbelbau",
               "Prüft Holzarten, Jahresringe, verdeckte Fächer und konstruktive Holzverbindungen."),
    Profession("BOETTCHER", "Böttcher / Küfer", "Böttcherin / Küferin", "🛢️", 
               "Fassbau, Daubenfügung & Dichtigkeitsprüfung",
               "Beurteilt Fassvolumina, Holzsaft-Einflüsse, Dichtigkeit und Lagerungsbedingungen."),

    # Landwirtschaft, Gartenbau & Umwelt
    Profession("BAUER", "Bauer / Landwirt", "Bäuerin / Landwirtin", "🌾", 
               "Agrarwirtschaft, Bodenfruchtbarkeit & Ernte",
               "Analysiert Bodenqualitäten, Erntezyklen, Saatgut und landwirtschaftliche Nutzflächen."),
    Profession("GAERTNER", "Gärtner", "Gärtnerin", "🪴", 
               "Pflanzenzucht, Gartenbau & Botanik",
               "Untersucht Bepflanzungsmuster, Bodenbeschaffenheit, Treibhausklimate und Gehölzkunde."),
    Profession("FLORIST", "Florist", "Floristin", "💐", 
               "Blumenkunst, Ästhetik & Symbolik",
               "Bewertet Floristik, Schnittblumenkonservierung, Farbdynamik und florale Symbolsprache."),
    Profession("MUELLER", "Müller", "Müllerin", "⚙️", 
               "Mühlenwesen, Getreidemahlung & Hydro-Kinetik",
               "Beurteilt Mahlgrade, Wasserrad-Antriebe, Windnutzung und Mehldurchsatz."),
    Profession("KOCH", "Koch", "Köchin", "🍳", 
               "Kulinarik, Zubereitung & Geschmackskomposition",
               "Prüft Zutatenkombinationen, Garverfahren, Bekömmlichkeit und kulinarische Ästhetik."),
    Profession("BAECKER", "Bäcker", "Bäckerin", "🥖", 
               "Teigführung, Gärung & Ofenhitze",
               "Untersucht Getreidemischungen, Fermentation, Backtemperaturen und Haltbarkeit."),
    Profession("BRAUER", "Braumeister", "Braumeisterin", "🍺", 
               "Sudhaus, Fermentation & Braukunst",
               "Analysiert Wasserhärte, Hopfenbitterstoffe, Hefestämme und Stammwürze."),
    Profession("WINZER", "Winzer", "Winzerin", "🍇", 
               "Weinbau, Oenologie & Kellerwirtschaft",
               "Bewertet Hanglagen, Öchslemomente, Terroir und Lagerungsfähigkeit."),
    Profession("FLEISCHER", "Fleischer / Metzger", "Fleischerin / Metzgerin", "🥩", 
               "Zerlegung, Haltbarmachung & Fleischwaren",
               "Untersucht Pökelverfahren, Reifegrade, Anatomie und Haltbarmachung."),

    # Tierhaltung, Veterinärwesen & Jagd
    Profession("TIERPFLEGER", "Tierpfleger / Tierwirt", "Tierpflegerin / Tierwirtin", "🐾", 
               "Tierzucht, Habitate & Tierhaltung",
               "Achtet auf Artgerechtigkeit, Fütterungszyklen, Verhaltensmuster und Gehegebau."),
    Profession("PFERDEWIRT", "Pferdewirt / Reitmeister", "Pferdewirtin / Reitmeisterin", "🐎", 
               "Pferdezucht, Equitation & Haltung",
               "Beurteilt Gangarten, Pferdeanatomie, Zuchtlinien, Sattelzeug und Stallhygiene."),
    Profession("FISCHWIRT", "Fischwirt", "Fischwirtin", "🐟", 
               "Aquakultur, Binnen- & Küstenfischerei",
               "Analysiert Gewässergüte, Fangtechniken, Fischbestände und Binnenfischerei."),
    Profession("REVIERJAEGER", "Revierjäger", "Revierjägerin", "🦌", 
               "Jagdwesen, Wildbiologie & Revierpflege",
               "Prüft Wildbestände, Spurenlesen, Äsungsflächen und jagdethische Grundlagen."),
    Profession("IMKER", "Imker", "Imkerin", "🐝", 
               "Apidologie, Wachsgewinnung & Trachtnetzwerke",
               "Beurteilt Bienenstock-Gesundheit, Wachsqualität, Propolis und Blütenquellen."),
    Profession("FORSTWIRT", "Forstwirt / Förster", "Forstwirtin / Försterin", "🌲", 
               "Sylvitektur, Bodenkunde & Waldnutzung",
               "Analysiert Holzressourcen, Ökosysteme, Baugrund und nachhaltige Bewirtschaftung."),
    Profession("GERBER", "Gerber", "Gerberin", "📜", 
               "Lederaufbereitung, Pergamenterzeugung & Gerbstoffe",
               "Untersucht Pergamentqualität, Pflanzengerbstoffe, Lederfestigkeit und Haltbarkeit."),

    # Wasser, Recycling & Umwelttechnik
    Profession("UMWELTTECHNOLOGE", "Umwelttechnologe", "Umwelttechnologin", "♻️", 
               "Abwasserbewirtschaftung, Kreislauf & Recycling",
               "Analysiert Stoffkreisläufe, Abwasserreinigung, Schadstoffentsorgung und Umweltauflagen."),

    # Rohstoff & Untertage
    Profession("KOEHLER", "Köhler", "Köhlerin", "🔥", 
               "Holzkohleerzeugung, Meilerführung & Pyrolyse",
               "Beurteilt Verkohlungsgrade, Meileraufbau, Brennwerte und Waldgewerbe."),
    Profession("BERGMANN", "Bergmann / Kumpel", "Bergfrau / Bergbauingenieurin", "⛏️", 
               "Montanwesen, Erzwelt & Untertagebau",
               "Prüft Stollenstabilität, Erzadern, Gesteinsschichten und unterirdische Hohlräume."),

    # Heilung, Geisteswissenschaft & Ordnung
    Profession("MEDICUS", "Arzt / Veterinär / Medicus", "Ärztin / Veterinärin / Medica", "⚕️", 
               "Diagnostik, Pharmakologie & Vitalstoffe",
               "Sucht nach biologischer Dynamik, Giften, Heilmitteln, Physis und pathologischen Spuren."),
    Profession("TFA", "Tiermedizinischer Fachangestellter", "Tiermedizinische Fachangestellte", "🩺", 
               "Veterinärmedizin, Behandlungsassistenz & Anästhesie",
               "Achtet auf Behandlungsabläufe, Hygiene, Probenentnahmen und tiermedizinische Instrumente."),
    Profession("AKADEMIKER", "Historiker", "Historikerin", "📜", 
               "Quellenkritik, Exegese & Chroniken",
               "Betreibt historische Kontextualisierung, Provenienzrecherche und paläographische Kritik."),
    Profession("PHILOSOPH", "Philosoph", "Philosophin", "🕯️", 
               "Epistemologie, Logik & Ethik",
               "Prüft Schlüssigkeit, ontologische Grundannahmen, Paradoxien und ethische Tragweite."),
    Profession("WAECHTER", "Wächter / Nachtwächter", "Wächterin / Nachtwächterin", "🗡️", 
               "Sicherheit, Torkontrolle & Chronometrie",
               "Prüft Zugangsrechte, Nachtruhe, Schwachstellen der Befestigung und Sicherheitsrisiken.")
]
